In [2]:
#Data cleaning
import pandas as pd
import numpy as np

In [3]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [4]:
data = pd.DataFrame(data)

In [5]:
data

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [7]:
data.isnull().sum()

Name          0
Age           1
Department    0
Salary        1
dtype: int64

In [9]:
data.dropna()

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
5    Alice  25.0         HR  50000.0

In [10]:
data.dropna(how = "any")

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
5    Alice  25.0         HR  50000.0

In [11]:
data.dropna(how = "all")

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [12]:
data["Age"].fillna(data["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [14]:
data["Salary"].fillna(data["Salary"].median())

0    50000.0
1    60000.0
2    70000.0
3    62000.0
4    60000.0
5    50000.0
Name: Salary, dtype: float64

In [17]:
data["Age"].fillna(method = "bfill") #backward fill/ forward fill

C:\Users\DIVYA\AppData\Local\Temp\ipykernel_17624\3956897996.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["Age"].fillna(method = "bfill")

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [20]:
data.dup = data[data.duplicated(keep = "last")]
data.dup

C:\Users\DIVYA\AppData\Local\Temp\ipykernel_17624\2807015400.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.dup = data[data.duplicated(keep = "last")]

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0

In [21]:
data = data.drop_duplicates()
data

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN

In [23]:
data["Promoted Salary"] = data["Salary"] * 10
data

C:\Users\DIVYA\AppData\Local\Temp\ipykernel_17624\1238949440.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Promoted Salary"] = data["Salary"] * 10

      Name   Age Department   Salary  Promoted Salary
0    Alice  25.0         HR  50000.0         500000.0
1      Bob  30.0         IT  60000.0         600000.0
2  Charlie  35.0    Finance  70000.0         700000.0
3    David   NaN         IT  62000.0         620000.0
4      Eve  29.0         HR      NaN              NaN

In [25]:
data["Promoted Salary"] = data["Promoted Salary"].apply(lambda x: x/10 if x > 650000 else x)
data

C:\Users\DIVYA\AppData\Local\Temp\ipykernel_17624\969077845.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Promoted Salary"] = data["Promoted Salary"].apply(lambda x: x/10 if x > 650000 else x)

      Name   Age Department   Salary  Promoted Salary
0    Alice  25.0         HR  50000.0         500000.0
1      Bob  30.0         IT  60000.0         600000.0
2  Charlie  35.0    Finance  70000.0          70000.0
3    David   NaN         IT  62000.0         620000.0
4      Eve  29.0         HR      NaN              NaN

In [27]:
# apply and lambda
def multiplying_age(x):
  return x*2

data["Age"] = data["Age"].apply(multiplying_age)

C:\Users\DIVYA\AppData\Local\Temp\ipykernel_17624\271528875.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Age"] = data["Age"].apply(multiplying_age)

In [28]:
data

      Name   Age Department   Salary  Promoted Salary
0    Alice  50.0         HR  50000.0         500000.0
1      Bob  60.0         IT  60000.0         600000.0
2  Charlie  70.0    Finance  70000.0          70000.0
3    David   NaN         IT  62000.0         620000.0
4      Eve  58.0         HR      NaN              NaN

In [29]:
data["Age"] = data["Age"].apply(lambda x: x/2)

C:\Users\DIVYA\AppData\Local\Temp\ipykernel_17624\1867776423.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Age"] = data["Age"].apply(lambda x: x/2)

In [30]:
data

      Name   Age Department   Salary  Promoted Salary
0    Alice  25.0         HR  50000.0         500000.0
1      Bob  30.0         IT  60000.0         600000.0
2  Charlie  35.0    Finance  70000.0          70000.0
3    David   NaN         IT  62000.0         620000.0
4      Eve  29.0         HR      NaN              NaN

In [38]:

department_info = {
    "Department": ["HR", "IT", "Finance"],
    "Location": ["New York", "San Francisco", "Chicago"],
    "Manager": ["Laura", "Steve", "Nina"]
}

df2 = pd.DataFrame(department_info)
df2

  Department       Location Manager
0         HR       New York   Laura
1         IT  San Francisco   Steve
2    Finance        Chicago    Nina

In [32]:
pd.concat([data,df2])

,Name,Age,Department,Salary,Promoted Salary,Dept,Location,Manager
0,Alice,25.0,HR,50000.0,500000.0,NaN,NaN,NaN
1,Bob,30.0,IT,60000.0,600000.0,NaN,NaN,NaN
2,Charlie,35.0,Finance,70000.0,70000.0,NaN,NaN,NaN
3,David,NaN,IT,62000.0,620000.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,HR,New York,Laura
1,NaN,NaN,NaN,NaN,NaN,IT,San Francisco,Steve
2,NaN,NaN,NaN,NaN,NaN,Finance,Chicago,Nina

In [33]:

pd.concat([data,df2], axis=1)

,Name,Age,Department,Salary,Promoted Salary,Dept,Location,Manager
0,Alice,25.0,HR,50000.0,500000.0,HR,New York,Laura
1,Bob,30.0,IT,60000.0,600000.0,IT,San Francisco,Steve
2,Charlie,35.0,Finance,70000.0,70000.0,Finance,Chicago,Nina
3,David,NaN,IT,62000.0,620000.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN

In [37]:
pd.merge(data, df2, on = "Deptartment")

KeyError: 'Deptartment'