In [1]:
import pandas as pd
import numpy as np

In [5]:
df= pd.read_csv("food_delivery.csv")
df

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
0,e5b99ed3-4bd6-4aed-9583-989823be022d,2025-04-10 13:21:00,2025-04-10 13:58:00,37.0,New York,NY,40.7128,-74.0060,Pasta Place,False,NaN,4.9
1,fd83af05-01fa-4b33-9254-b2708993a58a,2025-01-26 08:45:00,2025-01-26 09:06:00,21.0,Dallas,TX,32.7767,-96.7970,Taco Town,False,NaN,4.8
2,f4ab757f-669e-4b5a-9279-4b88a456fca8,2025-01-20 21:27:00,2025-01-20 22:22:00,55.0,San Jose,CA,37.3382,-121.8863,Burger Haven,False,NaN,4.1
3,8e4247d0-c211-445b-81c0-3d13e9101398,2024-12-12 16:17:00,2024-12-12 16:55:00,38.0,San Diego,CA,32.7157,-117.1611,Seafood Delight,False,NaN,4.7
4,65c2f48f-4a3c-4159-8eaf-22ae6a1fbff2,2025-03-01 14:24:00,2025-03-01 14:47:00,23.0,Philadelphia,PA,39.9526,-75.1652,The Gourmet Kitchen,False,NaN,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,cb598861-e313-4836-873d-93a788b8150c,2025-04-20 18:18:00,2025-04-20 19:07:00,49.0,Los Angeles,CA,34.0522,-118.2437,Taco Town,False,NaN,3.7
9996,475f4e9d-6288-4d22-8c62-0147faece970,2025-02-06 12:04:00,2025-02-06 13:11:00,67.0,San Antonio,TX,29.4241,-98.4936,Pasta Place,False,NaN,2.8
9997,9e9a46d2-5d11-4be8-9fd1-3640d431a976,2025-01-22 19:12:00,2025-01-22 19:48:00,36.0,San Antonio,TX,29.4241,-98.4936,Burger Haven,False,NaN,5.0
9998,aafe9464-69d4-4449-a6bf-5d392ddf14ab,2024-11-04 12:33:00,2024-11-04 13:52:00,79.0,San Jose,CA,37.3382,-121.8863,Bistro Belle,False,NaN,3.3
9999,def496b0-2729-4274-948f-c3956eeab6e4,2025-03-07 18:28:00,2025-03-07 19:52:00,84.0,Philadelphia,PA,39.9526,-75.1652,Taco Town,False,NaN,2.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               10000 non-null  object
 1   order_time             10000 non-null  object
 2   delivery_time          8961 non-null   object
 3   delivery_duration_min  8961 non-null   float64
 4   city                   10000 non-null  object
 5   state                  10000 non-null  object
 6   latitude               10000 non-null  float64
 7   longitude              10000 non-null  float64
 8   restaurant             10000 non-null  object
 9   is_canceled            10000 non-null  bool
 10  cancel_reason          1039 non-null   object
 11  customer_rating        8961 non-null   float64
dtypes: bool(1), float64(4), object(7)
memory usage: 869.3+ KB

In [7]:
df.head()

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
0,e5b99ed3-4bd6-4aed-9583-989823be022d,2025-04-10 13:21:00,2025-04-10 13:58:00,37.0,New York,NY,40.7128,-74.0060,Pasta Place,False,NaN,4.9
1,fd83af05-01fa-4b33-9254-b2708993a58a,2025-01-26 08:45:00,2025-01-26 09:06:00,21.0,Dallas,TX,32.7767,-96.7970,Taco Town,False,NaN,4.8
2,f4ab757f-669e-4b5a-9279-4b88a456fca8,2025-01-20 21:27:00,2025-01-20 22:22:00,55.0,San Jose,CA,37.3382,-121.8863,Burger Haven,False,NaN,4.1
3,8e4247d0-c211-445b-81c0-3d13e9101398,2024-12-12 16:17:00,2024-12-12 16:55:00,38.0,San Diego,CA,32.7157,-117.1611,Seafood Delight,False,NaN,4.7
4,65c2f48f-4a3c-4159-8eaf-22ae6a1fbff2,2025-03-01 14:24:00,2025-03-01 14:47:00,23.0,Philadelphia,PA,39.9526,-75.1652,The Gourmet Kitchen,False,NaN,4.6

In [8]:
df.tail()

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
9995,cb598861-e313-4836-873d-93a788b8150c,2025-04-20 18:18:00,2025-04-20 19:07:00,49.0,Los Angeles,CA,34.0522,-118.2437,Taco Town,False,NaN,3.7
9996,475f4e9d-6288-4d22-8c62-0147faece970,2025-02-06 12:04:00,2025-02-06 13:11:00,67.0,San Antonio,TX,29.4241,-98.4936,Pasta Place,False,NaN,2.8
9997,9e9a46d2-5d11-4be8-9fd1-3640d431a976,2025-01-22 19:12:00,2025-01-22 19:48:00,36.0,San Antonio,TX,29.4241,-98.4936,Burger Haven,False,NaN,5.0
9998,aafe9464-69d4-4449-a6bf-5d392ddf14ab,2024-11-04 12:33:00,2024-11-04 13:52:00,79.0,San Jose,CA,37.3382,-121.8863,Bistro Belle,False,NaN,3.3
9999,def496b0-2729-4274-948f-c3956eeab6e4,2025-03-07 18:28:00,2025-03-07 19:52:00,84.0,Philadelphia,PA,39.9526,-75.1652,Taco Town,False,NaN,2.0

In [9]:
df.describe()

       delivery_duration_min      latitude     longitude  customer_rating
count            8961.000000  10000.000000  10000.000000      8961.000000
mean               49.369490     35.179529    -99.659819         3.916416
std                17.655349      4.260429     16.537018         0.895868
min                20.000000     29.424100   -121.886300         1.000000
25%                36.000000     32.715700   -117.161100         3.500000
50%                47.000000     34.052200    -98.493600         4.100000
75%                59.000000     39.952600    -87.629800         4.600000
max                90.000000     41.878100    -74.006000         5.000000

In [11]:
df.columns

Index(['order_id', 'order_time', 'delivery_time', 'delivery_duration_min',
       'city', 'state', 'latitude', 'longitude', 'restaurant', 'is_canceled',
       'cancel_reason', 'customer_rating'],
      dtype='object')

In [13]:
df.shape

(10000, 12)

In [14]:
df.dtypes

order_id                  object
order_time                object
delivery_time             object
delivery_duration_min    float64
city                      object
state                     object
latitude                 float64
longitude                float64
restaurant                object
is_canceled                 bool
cancel_reason             object
customer_rating          float64
dtype: object

In [15]:
#Data cleaning
df.isnull().sum()

order_id                    0
order_time                  0
delivery_time            1039
delivery_duration_min    1039
city                        0
state                       0
latitude                    0
longitude                   0
restaurant                  0
is_canceled                 0
cancel_reason            8961
customer_rating          1039
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [27]:
df["delivery_duration_min"] = df[
    "delivery_duration_min"
].fillna(
    df["delivery_duration_min"].mean()
)

df["customer_rating"] = df[
    "customer_rating"
].fillna(
    df["customer_rating"].mean()
)

In [28]:
df

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
0,e5b99ed3-4bd6-4aed-9583-989823be022d,2025-04-10 13:21:00,NaN,37.0,New York,NY,40.7128,-74.0060,Pasta Place,False,NaN,4.9
1,fd83af05-01fa-4b33-9254-b2708993a58a,2025-01-26 08:45:00,NaN,21.0,Dallas,TX,32.7767,-96.7970,Taco Town,False,NaN,4.8
2,f4ab757f-669e-4b5a-9279-4b88a456fca8,2025-01-20 21:27:00,NaN,55.0,San Jose,CA,37.3382,-121.8863,Burger Haven,False,NaN,4.1
3,8e4247d0-c211-445b-81c0-3d13e9101398,2024-12-12 16:17:00,NaN,38.0,San Diego,CA,32.7157,-117.1611,Seafood Delight,False,NaN,4.7
4,65c2f48f-4a3c-4159-8eaf-22ae6a1fbff2,2025-03-01 14:24:00,NaN,23.0,Philadelphia,PA,39.9526,-75.1652,The Gourmet Kitchen,False,NaN,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,cb598861-e313-4836-873d-93a788b8150c,2025-04-20 18:18:00,NaN,49.0,Los Angeles,CA,34.0522,-118.2437,Taco Town,False,NaN,3.7
9996,475f4e9d-6288-4d22-8c62-0147faece970,2025-02-06 12:04:00,NaN,67.0,San Antonio,TX,29.4241,-98.4936,Pasta Place,False,NaN,2.8
9997,9e9a46d2-5d11-4be8-9fd1-3640d431a976,2025-01-22 19:12:00,NaN,36.0,San Antonio,TX,29.4241,-98.4936,Burger Haven,False,NaN,5.0
9998,aafe9464-69d4-4449-a6bf-5d392ddf14ab,2024-11-04 12:33:00,NaN,79.0,San Jose,CA,37.3382,-121.8863,Bistro Belle,False,NaN,3.3
9999,def496b0-2729-4274-948f-c3956eeab6e4,2025-03-07 18:28:00,NaN,84.0,Philadelphia,PA,39.9526,-75.1652,Taco Town,False,NaN,2.0

In [45]:
df.isnull().sum()

order_id                 0
order_time               0
delivery_duration_min    0
city                     0
state                    0
latitude                 0
longitude                0
restaurant               0
is_canceled              0
cancel_reason            0
customer_rating          0
dtype: int64

In [46]:
df["order_time"].value_counts()

order_time
2025-01-17 18:19:00    3
2025-04-17 19:00:00    3
2025-03-04 19:27:00    3
2025-01-18 13:58:00    3
2024-12-02 20:32:00    3
                      ..
2024-12-31 10:59:00    1
2025-03-18 08:43:00    1
2025-04-03 12:04:00    1
2024-12-05 14:09:00    1
2024-12-29 12:52:00    1
Name: count, Length: 9622, dtype: int64

In [47]:
df["city"].unique()

array(['New York', 'Dallas', 'San Jose', 'San Diego', 'Philadelphia',
       'Houston', 'Chicago', 'Los Angeles', 'San Antonio', 'Phoenix'],
      dtype=object)

In [48]:
df["delivery_duration_min"].nunique()

72

In [50]:
df.groupby("city")["delivery_duration_min"].mean()

city
Chicago         49.029581
Dallas          49.704614
Houston         49.147365
Los Angeles     48.722312
New York        49.829288
Philadelphia    49.936976
Phoenix         49.344856
San Antonio     49.763711
San Diego       49.522649
San Jose        48.689009
Name: delivery_duration_min, dtype: float64